const HENS = [
  // BROWN EGG LAYERS
  { id:1, name:"Hen Solo", breed:"Rhode Island Red", pun:"She lays in cold blood — cold hands, warm eggs.", personality:"Loner, street-smart, always suspicious of the rooster", eggColor:"brown", eggsPerYear:280, eggShade:"#A0522D", trait:"Brave", tagline:"I know.", feather:"#8B3A0F" },
  { id:2, name:"Cluck Norris", breed:"Barred Plymouth Rock", pun:"She roundhouse kicks the competition — daily.", personality:"No-nonsense, the enforcer of the flock", eggColor:"brown", eggsPerYear:265, eggShade:"#A0522D", trait:"Fierce", tagline:"Don't cross the pecking line.", feather:"#4A4A4A" },
  { id:3, name:"Oprah Henfrey", breed:"Rhode Island Red", pun:"You get an egg! You get an egg! EVERYBODY GETS AN EGG!", personality:"Generous, theatrical, motivational speaker of the coop", eggColor:"brown", eggsPerYear:290, eggShade:"#8B4513", trait:"Generous", tagline:"Live your best cluck.", feather:"#7B2D00" },
  { id:4, name:"Yolko Ono", breed:"Black Australorp", pun:"Her art divides the flock — love her or scramble.", personality:"Avant-garde, misunderstood creative genius", eggColor:"brown", eggsPerYear:250, eggShade:"#6B3A2A", trait:"Artsy", tagline:"Imagine no hunger.", feather:"#1A1A1A" },
  { id:5, name:"Feather Locklear", breed:"Barred Plymouth Rock", pun:"She's been in the nest since '81 and still going strong.", personality:"Ageless beauty, drama queen, fabulous", eggColor:"brown", eggsPerYear:260, eggShade:"#8B4513", trait:"Glamorous", tagline:"I lay to live.", feather:"#555555" },
  { id:6, name:"Hennifer Lopez", breed:"Rhode Island Red", pun:"From the block to the flock — her eggs don't stop.", personality:"High energy, always performing, tail feathers immaculate", eggColor:"brown", eggsPerYear:295, eggShade:"#A0522D", trait:"Performer", tagline:"Let's get loud... in the coop.", feather:"#8B2500" },
  { id:7, name:"Beak-Yoncé", breed:"Black Australorp", pun:"Who runs the world? Hens.", personality:"Iconic, flawless, releases eggs without announcement", eggColor:"brown", eggsPerYear:300, eggShade:"#7A3B1E", trait:"Iconic", tagline:"I woke up like this.", feather:"#1C1C1C" },
  { id:8, name:"Meryl Cheep", breed:"Barred Plymouth Rock", pun:"She's won so many 'Best Nest' awards, they named a category after her.", personality:"Method actress, takes every nest seriously, Oscar-worthy clucks", eggColor:"brown", eggsPerYear:255, eggShade:"#8B4513", trait:"Serious", tagline:"I could've been a centerpiece.", feather:"#666666" },
  { id:9, name:"Hennibal Lecter", breed:"Welsummer", pun:"I'd like to invite you to dinner. I'm having eggs.", personality:"Eerily calm, stares too long, eats silently and with precision", eggColor:"brown", eggsPerYear:170, eggShade:"#7B3F20", trait:"Intense", tagline:"Chianti pairs well with yolk.", feather:"#5C3A1E" },
  { id:10, name:"Cluckleberry Finn", breed:"Buckeye", pun:"Adventures down the Mississippi River — of feed.", personality:"Free-spirited, always looking for the horizon beyond the fence", eggColor:"brown", eggsPerYear:200, eggShade:"#A0522D", trait:"Adventurous", tagline:"Ain't no fence big enough.", feather:"#8B4513" },
  { id:11, name:"Maya Hengelou", breed:"Dominique", pun:"Still she lays. Still she lays. Still she lays.", personality:"Dignified, poetic, her cackle brings tears to the flock", eggColor:"brown", eggsPerYear:230, eggShade:"#7B3F20", trait:"Wise", tagline:"I know why the caged hen sings.", feather:"#3D3D3D" },
  { id:12, name:"Eggatha Christie", breed:"Sussex", pun:"The mystery is never 'who laid it' — it's always her.", personality:"Keeps everyone guessing, lays in unexpected spots", eggColor:"brown", eggsPerYear:245, eggShade:"#A0522D", trait:"Mysterious", tagline:"Everyone's a suspect.", feather:"#D4C9A8" },

  // WHITE EGG LAYERS
  { id:13, name:"Audrey Hepbeak", breed:"Leghorn", pun:"Breakfast at Tiffany's? She prefers breakfast FROM herself.", personality:"Refined, graceful, always impeccably groomed", eggColor:"white", eggsPerYear:300, eggShade:"#F5F0E8", trait:"Elegant", tagline:"Nothing is impossible.", feather:"#F5F5F5" },
  { id:14, name:"Eggspresso Dolores", breed:"California White", pun:"Rich, bold, and gone before you know it.", personality:"Fast-paced, buzzing with energy, never stops moving", eggColor:"white", eggsPerYear:310, eggShade:"#FFFFF0", trait:"Energetic", tagline:"Extra shot, every day.", feather:"#E8E8E8" },
  { id:15, name:"Princess Lay-a", breed:"White Leghorn", pun:"Help me, Obi-Wan. You're my only yolk.", personality:"Regal, dramatic, treats every nest like the Rebellion depends on it", eggColor:"white", eggsPerYear:320, eggShade:"#FFFFF0", trait:"Regal", tagline:"Aren't you a little short for a rooster?", feather:"#FAFAFA" },
  { id:16, name:"Cleopectra", breed:"Ancona", pun:"Queen of the Nile — and of the laying box.", personality:"Commands attention, expects tribute in the form of scratch feed", eggColor:"white", eggsPerYear:220, eggShade:"#F5F0E8", trait:"Commanding", tagline:"I did not come this far to be scrambled.", feather:"#CCCCCC" },
  { id:17, name:"Dolly Parthen", breed:"Leghorn", pun:"It takes a lot of feed to look this cheap.", personality:"Sweet, unpretentious, and somehow glamorous in a farmyard", eggColor:"white", eggsPerYear:295, eggShade:"#FFFFF0", trait:"Charming", tagline:"Lay it where the sun don't shine.", feather:"#F0F0F0" },
  { id:18, name:"Winona Ryder", breed:"Hamburg", pun:"She lays fast and leaves before anyone notices.", personality:"Mysterious exits, always in a hurry, surprisingly prolific", eggColor:"white", eggsPerYear:200, eggShade:"#F5F0E8", trait:"Elusive", tagline:"I just needed the eggs.", feather:"#B0B0B0" },
  { id:19, name:"Annette Feathering", breed:"California White", pun:"She starred in every dawn — before the world woke up.", personality:"Early riser, theatrical, always performing for an empty theater", eggColor:"white", eggsPerYear:285, eggShade:"#FFFFF0", trait:"Dramatic", tagline:"The nest is my stage.", feather:"#DADADA" },
  { id:20, name:"Greta Garbo", breed:"White Leghorn", pun:"I vant to be alone. (Unless you have scratch.)", personality:"Solitary, iconic, refuses to perform for the group", eggColor:"white", eggsPerYear:280, eggShade:"#F5F0E8", trait:"Solitary", tagline:"I don't want to be alone. I want to be left alone.", feather:"#F2F2F2" },
  { id:21, name:"Eggma Stone", breed:"Leghorn", pun:"Easy A — every single day.", personality:"Eager to please, bright-eyed, best in class at everything", eggColor:"white", eggsPerYear:305, eggShade:"#FFFFF0", trait:"Bright", tagline:"La La Lay.", feather:"#EEEEEE" },
  { id:22, name:"Florence Nighthen-gale", breed:"Hamburg", pun:"She tends to the wounded and heals them — with eggs.", personality:"Compassionate, nurturing, first responder of the flock", eggColor:"white", eggsPerYear:210, eggShade:"#F5F0E8", trait:"Nurturing", tagline:"I am a nurse, not a machine. A chicken nurse.", feather:"#C5C5C5" },
  { id:23, name:"Hatching Thatcher", breed:"Leghorn", pun:"Not for turning. The eggs, however, need turning.", personality:"Iron-willed, does not negotiate, lays on her own schedule", eggColor:"white", eggsPerYear:270, eggShade:"#FFFFF0", trait:"Stubborn", tagline:"The egg lady's not for turning.", feather:"#E5E5E5" },
  { id:24, name:"Clucker Monroe", breed:"California White", pun:"If you can't handle her at her noisiest, you don't deserve her at breakfast.", personality:"All-consuming presence, breathy cackle, magnetic to every rooster", eggColor:"white", eggsPerYear:275, eggShade:"#F5F0E8", trait:"Magnetic", tagline:"Happy birthday, Mr. Farmer.", feather:"#EFEFEF" },

  // BLUE / GREEN EGG LAYERS
  { id:25, name:"Teal Swiftfeather", breed:"Araucana", pun:"We are never ever ever eating this egg. Never.", personality:"Dramatic fallouts, writes songs about the dog, comes back stronger", eggColor:"blue", eggsPerYear:180, eggShade:"#87CEEB", trait:"Resilient", tagline:"Got a long list of ex-roosters.", feather:"#A78B6F" },
  { id:26, name:"Araucana Grande", breed:"Araucana", pun:"Thank U, Next (egg).", personality:"Ponytail always perfect, lays blue eggs with zero apology", eggColor:"blue", eggsPerYear:175, eggShade:"#89CFF0", trait:"Confident", tagline:"Thank U, Next yolk.", feather:"#7D6B5E" },
  { id:27, name:"Indigo Jones", breed:"Easter Egger", pun:"It belongs in a nest! (The egg. It belongs in a nest.)", personality:"Adventure-seeking, loses her eggs in the craziest places", eggColor:"blue", eggsPerYear:200, eggShade:"#6495ED", trait:"Bold", tagline:"Eggs. Why'd it have to be eggs.", feather:"#9B8B7A" },
  { id:28, name:"Aqua Fawcett", breed:"Easter Egger", pun:"Her eggs glitter more than her feathers.", personality:"Radiant, 70s energy, magnificent fluffy hairdo", eggColor:"blue", eggsPerYear:195, eggShade:"#7FFFD4", trait:"Radiant", tagline:"I had the most remarkable nest.", feather:"#C0A882" },
  { id:29, name:"Celeste Holm", breed:"Cream Legbar", pun:"She always steals every scene — and every egg.", personality:"Scene-stealer, generous, quietly legendary", eggColor:"blue", eggsPerYear:185, eggShade:"#B0E0E6", trait:"Generous", tagline:"Always the supporting actress, never the scramble.", feather:"#B8A090" },
  { id:30, name:"Lady Bluebell", breed:"Cream Legbar", pun:"She lays with the elegance of royalty and the pace of a postman.", personality:"Stately, consistent, never in a rush, always on time", eggColor:"blue", eggsPerYear:190, eggShade:"#ADD8E6", trait:"Elegant", tagline:"One simply lays.", feather:"#D4BEA8" },
  { id:31, name:"Mintoo Holly-feather", breed:"Easter Egger", pun:"Her eggs are cooler than the coop on a January morning.", personality:"Chill, unbothered, does everything at her own temperature", eggColor:"green", eggsPerYear:200, eggShade:"#98FB98", trait:"Chill", tagline:"Everything's mint.", feather:"#A89080" },
  { id:32, name:"Sage Windsor", breed:"Olive Egger", pun:"Olive — as in, she'll lay olive green eggs until she's good and ready.", personality:"Aristocratic demeanor, lays only when the conditions are perfect", eggColor:"green", eggsPerYear:160, eggShade:"#6B8E23", trait:"Selective", tagline:"One does not simply rush.", feather:"#8B7355" },
  { id:33, name:"Fern Gully", breed:"Easter Egger", pun:"The forest called. It wants its egg color back.", personality:"Nature-loving, always dustbathing in fresh dirt, earthy vibes", eggColor:"green", eggsPerYear:195, eggShade:"#4F7942", trait:"Earthy", tagline:"Save the coop. Save the world.", feather:"#9B8065" },
  { id:34, name:"Olive Oyl", breed:"Olive Egger", pun:"She's thin as a rail but her eggs are thick with flavor.", personality:"Energetic, squeaky voice, Popeye obsessed, eats spinach by the bucket", eggColor:"green", eggsPerYear:155, eggShade:"#808000", trait:"Spirited", tagline:"Ohhhh Popeye!", feather:"#7A6040" },
  { id:35, name:"Cress Witherspoon", breed:"Easter Egger", pun:"Legally Blonde? Please. Legally Green.", personality:"Overachiever, took the bar exam, still graduated top of her nest", eggColor:"green", eggsPerYear:205, eggShade:"#7CB518", trait:"Driven", tagline:"What, like it's hard?", feather:"#AA9070" },
  { id:36, name:"Jade Pinkett Hen", breed:"Olive Egger", pun:"She laid the eggs, produced the eggs, and directed the eggs.", personality:"Multitasker, always working on three projects, inspires the whole flock", eggColor:"green", eggsPerYear:165, eggShade:"#00A86B", trait:"Driven", tagline:"I choose me.", feather:"#6E5540" },

  // SPECKLED / CHOCOLATE EGG LAYERS
  { id:37, name:"Maron-ella DeVille", breed:"Marans", pun:"Cruella's second cousin. The only thing she harms is cholesterol.", personality:"Dramatic entrance, spectacular dark eggs, absolutely unapologetic", eggColor:"chocolate", eggsPerYear:150, eggShade:"#3D1C02", trait:"Bold", tagline:"Darling, I am the darkest egg in the box.", feather:"#2A2A2A" },
  { id:38, name:"Velvet Darko", breed:"Black Copper Marans", pun:"Her eggs are so dark, scientists study them for scientific reasons.", personality:"Brooding, existential, eats quietly and contemplates everything", eggColor:"chocolate", eggsPerYear:145, eggShade:"#4A1500", trait:"Brooding", tagline:"Every living thing dies alone.", feather:"#1A1A1A" },
  { id:39, name:"Cocoa Chanel", breed:"Black Copper Marans", pun:"Luxury is when simplicity eclipses everything. Or a really dark egg.", personality:"Effortlessly chic, refuses to over-accessorize her feathers", eggColor:"chocolate", eggsPerYear:155, eggShade:"#5C2500", trait:"Chic", tagline:"Fashion fades, eggs remain.", feather:"#2E1500" },
  { id:40, name:"Brownie Boop", breed:"Welsummer", pun:"She's cute, she's spotty, and she never skips egg day.", personality:"Cheerful, bubbly, leaves speckled eggs like little gifts", eggColor:"speckled", eggsPerYear:170, eggShade:"#A0522D", trait:"Cheerful", tagline:"Boop!", feather:"#7B4F20" },
  { id:41, name:"Freckle McFluff", breed:"Speckled Sussex", pun:"She's spotted, she's speckled, and she owns every freckle.", personality:"Proudly patterned, zero self-consciousness, life of the party", eggColor:"speckled", eggsPerYear:245, eggShade:"#8B6914", trait:"Confident", tagline:"Own your spots.", feather:"#8B5C2A" },
  { id:42, name:"Specky Spears", breed:"Speckled Sussex", pun:"Oops, she did it again — laid another perfect spotted egg.", personality:"Pop star energy, comeback queen, speckled eggs are her brand", eggColor:"speckled", eggsPerYear:240, eggShade:"#A07850", trait:"Flashy", tagline:"It's Specky, scratch.", feather:"#7B4520" },

  // CREAM / TINTED EGG LAYERS
  { id:43, name:"Carmel-ita Banana", breed:"Buff Orpington", pun:"Sweet as caramel, plump as a pillow, lays like a dream.", personality:"The big soft friend everyone loves, warmest hen in the flock", eggColor:"cream", eggsPerYear:200, eggShade:"#F5E6C8", trait:"Warm", tagline:"Everything is butter.", feather:"#D4A853" },
  { id:44, name:"Goldie Hen", breed:"Buff Orpington", pun:"She's golden. Her eggs are golden. Everything she touches is golden.", personality:"Optimistic to a fault, golden aura, radiates warmth", eggColor:"cream", eggsPerYear:205, eggShade:"#F5E6B0", trait:"Sunny", tagline:"Good things are comin'.", feather:"#D4A030" },
  { id:45, name:"Buttercup McBeak", breed:"Buff Orpington", pun:"As soft and rich as her name, as dependable as dawn.", personality:"Sweet, gentle, goes to bed the earliest and wakes up ready", eggColor:"cream", eggsPerYear:195, eggShade:"#FFF8DC", trait:"Gentle", tagline:"Start your day with butter.", feather:"#D4A060" },
  { id:46, name:"Vanilla Ice Cream", breed:"Leghorn x Orpington", pun:"Stop! Collaborate and lay.", personality:"90s energy, extremely pale feathers, surprisingly edgy", eggColor:"cream", eggsPerYear:215, eggShade:"#FFFDD0", trait:"Edgy", tagline:"Ice, ice, eggy.", feather:"#F0F0E0" },
  { id:47, name:"Sandy Eggo", breed:"Delaware", pun:"Tell me more, tell me more — did she lay right away?", personality:"Grease is her era, sandy blonde and unbothered", eggColor:"cream", eggsPerYear:220, eggShade:"#F5DEB3", trait:"Cool", tagline:"Hopelessly devoted to this nest.", feather:"#E0D0A0" },
  { id:48, name:"Mavis Beakon", breed:"Dominique", pun:"She's guided more hens to the nest box than any GPS.", personality:"Reliable, directional instincts, never loses her way", eggColor:"cream", eggsPerYear:230, eggShade:"#EDD9A3", trait:"Reliable", tagline:"Recalculating route to the nest.", feather:"#606060" },

  // BANTAM & SPECIALTY
  { id:49, name:"Tiny Turner", breed:"Old English Game Bantam", pun:"Simply the breast. Better than all the rest.", personality:"What she lacks in size she makes for in volume and personality", eggColor:"cream", eggsPerYear:110, eggShade:"#F5E6C8", trait:"Fierce", tagline:"We don't need another birdcage.", feather:"#8B6A30" },
  { id:50, name:"Micki Minaj", breed:"Silkie Bantam", pun:"She came in like a wrecking ball — of fluff.", personality:"Outrageous, extravagant plumage, walks like she's on a runway", eggColor:"cream", eggsPerYear:100, eggShade:"#F5E0C8", trait:"Extra", tagline:"Anaconda don't want none unless you got eggs, hun.", feather:"#E8D8B0" },
  { id:51, name:"Fluffy McPuffy", breed:"Silkie", pun:"She looks like a cloud that figured out how to walk.", personality:"Perpetually confused, endlessly fluffy, somehow lays eggs perfectly", eggColor:"cream", eggsPerYear:105, eggShade:"#FFF0E0", trait:"Fluffy", tagline:"What is going on.", feather:"#F0EAD6" },
  { id:52, name:"Dolores Umbeak", breed:"Silkie", pun:"I will have order! And also eggs.", personality:"Pink obsessed, strict about nest rules, deeply unsettling smile", eggColor:"cream", eggsPerYear:100, eggShade:"#FAEBD7", trait:"Strict", tagline:"You will keep your beaks shut.", feather:"#F5C5C5" },
  { id:53, name:"Featherine Hepburn", breed:"Frizzle", pun:"She moves with purpose — and also, have you seen her feathers?", personality:"Curly-feathered wildcard, always on-brand, intellectually magnetic", eggColor:"cream", eggsPerYear:165, eggShade:"#F5E6C8", trait:"Eccentric", tagline:"I never lose. I either win or I molt.", feather:"#C8A870" },
  { id:54, name:"Frizzle Fitzgerald", breed:"Frizzle", pun:"So we nest on, boats against the current, feathers into the past.", personality:"Romantic, nostalgic, curly feathers in the wind, gazes at sunsets", eggColor:"cream", eggsPerYear:160, eggShade:"#F5E0B0", trait:"Romantic", tagline:"Can't repeat the past? Cluck.", feather:"#C0A865" },

  // MORE BROWN EGG LAYERS
  { id:55, name:"Ruth Bader Ginsberg-Cluck", breed:"New Hampshire Red", pun:"When there are nine of me in the nest box, then enough will have been said.", personality:"Dissents loudly, works the hardest, fights for every hen's rights", eggColor:"brown", eggsPerYear:250, eggShade:"#A0522D", trait:"Just", tagline:"Fight for the things you care about.", feather:"#8B3A0F" },
  { id:56, name:"Harriet Tubhen", breed:"Dominique", pun:"She led 70 other hens to safety — one fence at a time.", personality:"Fearless, tireless, legend in and out of the coop", eggColor:"brown", eggsPerYear:230, eggShade:"#8B4513", trait:"Fearless", tagline:"I never ran my train off the track.", feather:"#3A3A3A" },
  { id:57, name:"Rosa Perch", breed:"Rhode Island Red", pun:"She refused to give up her nest box. History was made.", personality:"Quiet dignity, immovable when it counts, changes the world by sitting still", eggColor:"brown", eggsPerYear:275, eggShade:"#A0522D", trait:"Dignified", tagline:"You must never be fearful of what you are doing when it is right.", feather:"#7A2A00" },
  { id:58, name:"Gloria Steinhen", breed:"Plymouth Rock", pun:"A hen needs a rooster like a fish needs a bicycle.", personality:"Independent, visionary, started the first hen-run nest collective", eggColor:"brown", eggsPerYear:255, eggShade:"#8B4513", trait:"Independent", tagline:"We are the leaders we've been looking for.", feather:"#555555" },
  { id:59, name:"Eggabeth Warren", breed:"New Hampshire Red", pun:"I have a plan for that egg.", personality:"Data-driven, plan for everything, twelve-point position on corn", eggColor:"brown", eggsPerYear:265, eggShade:"#A0522D", trait:"Methodical", tagline:"I have a plan for that.", feather:"#8B3A10" },
  { id:60, name:"Cluck Darwin", breed:"Sussex", pun:"Survival of the fluffiest.", personality:"Observational, scientific, takes notes on everything in the yard", eggColor:"brown", eggsPerYear:240, eggShade:"#8B4513", trait:"Curious", tagline:"It is not the strongest who survives, but the one who lays consistently.", feather:"#C8B09A" },
];
